package tamizdat

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"fmt"
	"math/big"
	"time"
)

// defunctCAEntry bundles a curated defunct-CA distinguished name with its
// real historical NotBefore/NotAfter validity dates. We need both because
// (review F-RR-1) a censor with access to public CA records can compare a
// generated padding cert's Subject CN to its validity period: a cert
// claiming to be "VeriSign Class 3 ... G5" that was supposedly issued
// `time.Now() - 1 year` is provably impossible (real G5 roots were issued
// 2006-11-08), turning every padding cert into an instant detection signal.
// Anchoring NotBefore/NotAfter to the real CA's published validity period
// closes that oracle.
type defunctCAEntry struct {
	Subject   pkix.Name
	NotBefore time.Time
	NotAfter  time.Time
}

// defunctRootCAEntries is a curated pool of real, well-known root-CA
// distinguished names that have been distrusted / withdrawn from the WebPKI
// trust stores but which still appear in millions of historical CT-log
// entries. Using one of these as the Subject (and therefore also the
// Issuer, since each padding cert is self-signed) keeps the rendered chain
// string indistinguishable from a long-tail legacy CA that an observer
// might see in any large corpus, instead of a unique fabricated string
// ("Internet Trust Services Root R3" / "Edge TLS Intermediate CA <hex>",
// review F-4 finding) that survived as a high-cardinality fingerprint of
// our padding implementation.
//
// Each entry's NotBefore/NotAfter (review F-RR-1) is taken verbatim from
// the published validity period of the corresponding real CA root cert,
// so the generated padding cert's claimed issuance window is consistent
// with public-CT-log / CCADB data instead of being pinned to today.
//
// All entries are real CA Common Names that appear verbatim in public CT
// logs / Mozilla CCADB historical data:
//   - VeriSign G5 / G3: distrusted by Google/Mozilla 2018, ubiquitous in CT
//   - GeoTrust legacy roots: superseded by DigiCert post-2017 acquisition
//   - StartCom: distrusted 2017
//   - AddTrust External CA Root: distrusted 2020 (Sectigo expiry), enormous
//     CT log footprint as a former cross-sign anchor for Comodo/Sectigo;
//     swapped in for DigiNotar (review F-4 follow-up) because DigiNotar's
//     CT log frequency is ~8 entries vs millions for AddTrust, so AddTrust
//     blends into the long-tail more effectively.
var defunctRootCAEntries = []defunctCAEntry{
	{
		Subject: pkix.Name{
			Country:      []string{"US"},
			Organization: []string{"VeriSign, Inc."},
			OrganizationalUnit: []string{
				"VeriSign Trust Network",
				"(c) 2006 VeriSign, Inc. - For authorized use only",
			},
			CommonName: "VeriSign Class 3 Public Primary Certification Authority - G5",
		},
		NotBefore: time.Date(2006, 11, 8, 0, 0, 0, 0, time.UTC),
		NotAfter:  time.Date(2036, 7, 16, 23, 59, 59, 0, time.UTC),
	},
	{
		Subject: pkix.Name{
			Country:      []string{"US"},
			Organization: []string{"VeriSign, Inc."},
			OrganizationalUnit: []string{
				"VeriSign Trust Network",
				"(c) 1999 VeriSign, Inc. - For authorized use only",
			},
			CommonName: "VeriSign Class 3 Public Primary Certification Authority - G3",
		},
		NotBefore: time.Date(1999, 10, 1, 0, 0, 0, 0, time.UTC),
		NotAfter:  time.Date(2036, 7, 16, 23, 59, 59, 0, time.UTC),
	},
	{
		Subject: pkix.Name{
			Country:      []string{"US"},
			Organization: []string{"GeoTrust Inc."},
			CommonName:   "GeoTrust Global CA",
		},
		NotBefore: time.Date(2002, 5, 21, 4, 0, 0, 0, time.UTC),
		NotAfter:  time.Date(2022, 5, 21, 4, 0, 0, 0, time.UTC),
	},
	{
		Subject: pkix.Name{
			Country:      []string{"IL"},
			Organization: []string{"StartCom Ltd."},
			OrganizationalUnit: []string{
				"Secure Digital Certificate Signing",
			},
			CommonName: "StartCom Certification Authority",
		},
		NotBefore: time.Date(2006, 9, 17, 19, 46, 36, 0, time.UTC),
		NotAfter:  time.Date(2036, 9, 17, 19, 46, 36, 0, time.UTC),
	},
	{
		Subject: pkix.Name{
			Country:      []string{"SE"},
			Organization: []string{"AddTrust AB"},
			OrganizationalUnit: []string{
				"AddTrust External TTP Network",
			},
			CommonName: "AddTrust External CA Root",
		},
		NotBefore: time.Date(2000, 5, 30, 10, 48, 38, 0, time.UTC),
		NotAfter:  time.Date(2020, 5, 30, 10, 48, 38, 0, time.UTC),
	},
}

// pickDefunctEntry returns one curated defunct-CA entry (Subject DN +
// historical NotBefore/NotAfter), picked at random with crypto/rand.
// Caller-visible randomness keeps two padding chains generated by the same
// server from byte-aliasing on the Issuer field while still drawing only
// from real-CT-log-attested DNs.
func pickDefunctEntry() defunctCAEntry {
	max := big.NewInt(int64(len(defunctRootCAEntries)))
	idx, err := rand.Int(rand.Reader, max)
	if err != nil {
		// crypto/rand failure is an environment-level fault; fall back to
		// the first canonical entry rather than failing cert generation.
		return defunctRootCAEntries[0]
	}
	return defunctRootCAEntries[idx.Int64()]
}

// padCertChain appends N dummy CA-style certificates to the leaf cert's
// chain so that the encrypted Certificate message in the TLS 1.3 handshake
// approximates the byte-count of a real CDN cert chain (e.g. ok.ru -> ~3 certs,
// ~4 KB DER total). Without padding, our self-signed single cert (~1 KB) emits
// a noticeably smaller encrypted-flight than the masquerade target, giving an
// Aparecium-class detector a passive size-based signal even though TLS 1.3
// encrypts the certificate contents.
//
// The padding certs are valid X.509 (so TLS framing accepts them) but do NOT
// chain up to the leaf -- they're filler bytes that look like CA certificates
// to a passive observer. Clients with InsecureSkipVerify (our case) ignore
// them. Standard verifying clients would reject the connection at the
// Certificate verification step regardless, since our leaf is self-signed.
//
// targetExtraBytes is the byte floor for the padding; dummyCount is the cert
// floor. The loop runs until BOTH have been satisfied, i.e. it produces AT
// LEAST dummyCount certs AND at least targetExtraBytes of padding bytes.
// Typical: 3000-4000 bytes to match GlobalSign-class chains.
//
// F-4 follow-up (2026-05-09): the curated defunct-CA pool DN strings are
// 250-400 B shorter per cert than the original fabricated names, so 3 dummies
// no longer reach the 4200 B target the production call site requests
// (server.go:178). The previous early-exit `break` on `added >= target` was
// dead code under the new pool sizes; the new condition makes target a real
// floor instead of a stop-condition. A hard 16-cert safety cap prevents
// runaway in pathological RSA-key sizes.
func padCertChain(leafChain [][]byte, targetExtraBytes int, dummyCount int) ([][]byte, error) {
	if dummyCount <= 0 {
		dummyCount = 2
	}
	if targetExtraBytes <= 0 {
		targetExtraBytes = 3500
	}

	out := make([][]byte, 0, len(leafChain)+dummyCount+2)
	out = append(out, leafChain...)

	const safetyCap = 16
	added := 0
	for i := 0; (i < dummyCount || added < targetExtraBytes) && i < safetyCap; i++ {
		certDER, err := generateDummyCACert()
		if err != nil {
			return nil, fmt.Errorf("generating padding cert #%d: %w", i, err)
		}
		out = append(out, certDER)
		added += len(certDER)
	}
	return out, nil
}

// generateDummyCACert produces a self-signed RSA-2048 CA-looking certificate
// suitable for use as TLS chain padding. ~1.5 KB DER. The Subject and Issuer
// are randomized strings so two padding chains generated by the same server
// are not byte-identical (avoids a separate "twin-padding-cert" detector).
func generateDummyCACert() ([]byte, error) {
	priv, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return nil, err
	}

	// Random suffix to avoid identical Subject across instances.
	rb := make([]byte, 8)
	if _, err := rand.Read(rb); err != nil {
		return nil, err
	}
	suffix := fmt.Sprintf("%x", rb)

	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, err
	}

	// Pick a curated defunct-CA entry (Subject DN + real historical
	// validity dates) from the pool of real, distrusted-but-CT-logged root
	// CAs (review F-4). Earlier code used the fabricated string
	// "Edge TLS Intermediate CA <hex>" / "Internet Trust Services Root R3"
	// which has zero hits on the public internet and so served as a unique
	// fingerprint of our padding implementation. Because each padding cert
	// is self-signed (parent == tmpl in CreateCertificate), x509 renders
	// the parent's Subject into the cert's Issuer field, so setting
	// Subject from the curated pool drives both the Subject and Issuer
	// rendered strings.
	//
	// CommonName is suffixed with 16 random hex chars so two padding
	// chains generated by the same server are not byte-identical (see
	// TestPadCertChain_RandomizedSubjects). Real CT logs do contain many
	// per-issuance variants of the same root CN (different serials,
	// validity windows, key params) so a slight CN suffix divergence does
	// not stand out from the long-tail of historical entries.
	//
	// NotBefore/NotAfter are taken from the entry's real published
	// validity period (review F-RR-1) so the cert is consistent with
	// public CCADB / CT-log records instead of betraying the padding via
	// a today-anchored validity window.
	entry := pickDefunctEntry()
	subjectDN := entry.Subject
	subjectDN.CommonName = subjectDN.CommonName + " " + suffix
	tmpl := &x509.Certificate{
		SerialNumber:          serial,
		Subject:               subjectDN,
		Issuer:                subjectDN, // self-signed: x509 will use parent (= tmpl) Subject anyway
		NotBefore:             entry.NotBefore,
		NotAfter:              entry.NotAfter,
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
		BasicConstraintsValid: true,
		IsCA:                  true,
		MaxPathLenZero:        false,
		MaxPathLen:            1,
	}

	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &priv.PublicKey, priv)
	if err != nil {
		return nil, err
	}
	return der, nil
}
